'use strict';
const $=id=>document.getElementById(id);
let config,meshes,currentResult=null,lastRequest=null,requestSerial=0,plotReady=false,fullView=false;
const fmt=(n,d=0)=>Number(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const escapeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to complete lookup.');return data;}
function clearResult(){requestSerial++;currentResult=null;lastRequest=null;$('save').disabled=true;$('result-body').innerHTML='<p class="muted">Click “Locate in atlas” to check these coordinates.</p>';$('slices').innerHTML='<p class="muted">Locate the updated point to refresh these slices.</p>';$('error').hidden=true;$('save-status').textContent='';if(plotReady)Plotly.restyle('atlas-plot',{x:[[]],y:[[]],z:[[]]},[3,4,5]);}
function updateMode(){const ds=config.datasets[$('dataset').value],mode=$('mode').value;$('method-note').textContent=mode==='affine'&&ds.default_mode==='nonlinear'?'Affine-only comparison selected. The complete nonlinear correction is available in the menu.':ds.note;$('transform-badge').textContent=config.mode_labels[mode];$('transform-badge').classList.toggle('nonlinear',mode==='nonlinear');$('affine-toggle-wrap').hidden=mode!=='nonlinear';$('show-affine').checked=false;clearResult();}
function updateDataset(){const ds=config.datasets[$('dataset').value];$('mode').innerHTML=ds.modes.map(m=>`<option value="${m}">${config.mode_labels[m]}</option>`).join('');$('mode').value=ds.default_mode;$('mode').disabled=ds.modes.length===1;$('example').innerHTML='<option value="">Load an example…</option>'+ds.examples.map((e,i)=>`<option value="${i}">${escapeText(e.label)}</option>`).join('');updateMode();}
function parseCoordinates(){const text=$('coordinates').value.trim().replace(/[\[\]()]/g,'');const parts=text.split(/[\s,;]+/).filter(Boolean);const valid=/^[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i;if(parts.length!==3||!parts.every(p=>valid.test(p)&&Number.isFinite(Number(p))))throw Error('Enter exactly three numbers in X, Y, Z order. Paste the absolute location shown by Horta.');return parts.map(Number);}
function meshTrace(key,name,color,opacity){const m=meshes[key];return {type:'mesh3d',name,showlegend:false,x:m.vertices.map(v=>v[0]),y:m.vertices.map(v=>v[2]),z:m.vertices.map(v=>v[1]),i:m.faces.map(f=>f[0]),j:m.faces.map(f=>f[1]),k:m.faces.map(f=>f[2]),color,opacity,hoverinfo:'skip',flatshading:false,lighting:{ambient:.8,diffuse:.55},visible:key==='rn'?false:true};}
function focus(resetCamera=false){if(!plotReady)return;const p=currentResult?currentResult.ccf_ap_dv_ml_um.map(v=>v/1000):[9,4,5.7];const ranges=fullView?[[0,13.2],[0,11.4],[8,0]]:[[Math.min(7.55,p[0]-.45),Math.max(10.5,p[0]+.45)],[Math.min(3.4,p[2]-.45),Math.max(8,p[2]+.45)],[Math.max(5.2,p[1]+.45),Math.min(2.7,p[1]-.45)]];Plotly.relayout('atlas-plot',{'scene.xaxis.range':ranges[0],'scene.yaxis.range':ranges[1],'scene.zaxis.range':ranges[2],...(resetCamera?{'scene.camera':{eye:{x:1.55,y:1.65,z:.8},center:{x:0,y:0,z:0},up:{x:0,y:0,z:1}}}:{})});$('focus-mrn').classList.toggle('selected',!fullView);$('whole-brain').classList.toggle('selected',fullView);}
async function initPlot(){const axes=title=>({title:{text:title,font:{size:11,color:'#657b80'}},tickfont:{size:10,color:'#75858a'},gridcolor:'#e9eeee',zeroline:false,backgroundcolor:'#fff',showbackground:true});await Plotly.newPlot('atlas-plot',[meshTrace('brain','Brain','#c9d3d5',.07),meshTrace('mrn','MRN','#ddb24c',.28),meshTrace('rn','Red nucleus','#bd9dcb',.22),{type:'scatter3d',name:'Your point',mode:'markers',x:[],y:[],z:[],marker:{size:7,color:'#087a86',line:{color:'white',width:1.5}},hovertemplate:'Your point<br>AP %{x:.3f} mm<br>ML %{y:.3f} mm<br>DV %{z:.3f} mm<extra></extra>'},{type:'scatter3d',name:'Affine estimate',mode:'markers',x:[],y:[],z:[],visible:false,marker:{size:5,color:'#7f8992',symbol:'diamond'},hovertemplate:'Affine estimate<br>AP %{x:.3f} mm<br>ML %{y:.3f} mm<br>DV %{z:.3f} mm<extra></extra>'},{type:'scatter3d',mode:'lines',x:[],y:[],z:[],visible:false,line:{color:'#879398',width:3},hoverinfo:'skip'}],{paper_bgcolor:'#fff',margin:{l:0,r:0,t:0,b:0},showlegend:false,scene:{xaxis:axes('AP · mm'),yaxis:axes('ML · mm'),zaxis:axes('DV · mm'),aspectmode:'data',camera:{eye:{x:1.55,y:1.65,z:.8}}}},{responsive:true,displaylogo:false,displayModeBar:false,scrollZoom:true});plotReady=true;focus();}
function render(r){currentResult=r;$('save').disabled=false;const outside=r.inside_mrn===false,unknown=r.inside_mrn===null;const title=unknown?'Outside atlas volume':outside?'Outside MRN':'Inside MRN';const distanceTitle=unknown?'Distance to MRN':outside?'from the MRN boundary':'inside the MRN boundary';$('result-body').innerHTML=`<div class="result-title ${unknown?'unknown':outside?'outside':''}">${title}</div><p class="region-name"><strong>${escapeText(r.atlas_name)}</strong> <span class="muted">(${escapeText(r.atlas_acronym)})</span></p><div class="distance"><strong>${fmt(r.boundary_distance_um,1)} µm</strong>${distanceTitle}${r.within_100um_of_boundary?'<div><span class="near">Near boundary · within 100 µm</span></div>':''}</div><div class="coordinate-result">${['AP','DV','ML'].map((a,i)=>`<div><span>${a} · µm</span><strong>${fmt(r.ccf_ap_dv_ml_um[i],1)}</strong></div>`).join('')}</div><p class="result-small">${escapeText(r.hemisphere)} hemisphere<br>${escapeText(r.transform_label)} · dataset ${escapeText(r.dataset)}</p>${r.mode==='nonlinear'?`<p class="result-small">Nonlinear shift: <strong>${fmt(r.nonlinear_shift_um,1)} µm</strong><br>Affine alone: ${r.affine_inside_mrn?'inside':'outside'} MRN</p>`:''}`;
$('slices').innerHTML=r.slices.length?r.slices.map(s=>`<figure class="slice"><figcaption>${s.title}<span>${s.fixed_axis} = ${fmt(s.fixed_um/1000,3)} mm</span></figcaption><img src="${s.image}" alt="${s.title} atlas slice with MRN and the queried point"><div class="slice-axes">Horizontal: ${s.horizontal_axis} → · Vertical: ${s.vertical_axis} ↓</div></figure>`).join(''):'<p class="muted">This point is outside the atlas volume; no slice can be shown.</p>';
const p=r.ccf_ap_dv_ml_um.map(v=>v/1000),a=r.affine_ccf_ap_dv_ml_um.map(v=>v/1000);Plotly.restyle('atlas-plot',{x:[[p[0]]],y:[[p[2]]],z:[[p[1]]]},[3]);Plotly.restyle('atlas-plot',{x:[[a[0]]],y:[[a[2]]],z:[[a[1]]],visible:$('show-affine').checked&&r.mode==='nonlinear'},[4]);Plotly.restyle('atlas-plot',{x:[[a[0],p[0]]],y:[[a[2],p[2]]],z:[[a[1],p[1]]],visible:$('show-affine').checked&&r.mode==='nonlinear'},[5]);focus();}
async function runCheck(event){event?.preventDefault();const serial=++requestSerial;$('error').hidden=true;$('save-status').textContent='';let req;try{req={dataset:$('dataset').value,mode:$('mode').value,xyz:parseCoordinates()};}catch(e){$('error').textContent=e.message;$('error').hidden=false;return;}$('check').disabled=true;$('check').textContent='Checking atlas…';try{const result=await api('/api/check',req);if(serial!==requestSerial)return;lastRequest=req;render(result);}catch(e){if(serial===requestSerial){$('error').textContent=e.message;$('error').hidden=false;}}finally{$('check').disabled=false;$('check').innerHTML='Locate in atlas <span>→</span>';}}
$('lookup-form').addEventListener('submit',runCheck);$('dataset').addEventListener('change',updateDataset);$('mode').addEventListener('change',updateMode);$('coordinates').addEventListener('input',()=>{$('example').value='';clearResult();});$('example').addEventListener('change',()=>{if($('example').value==='')return;const e=config.datasets[$('dataset').value].examples[Number($('example').value)];$('coordinates').value='['+e.xyz.join(', ')+']';clearResult();});$('focus-mrn').addEventListener('click',()=>{fullView=false;focus(true);});$('whole-brain').addEventListener('click',()=>{fullView=true;focus(true);});$('show-rn').addEventListener('change',()=>{if(plotReady)Plotly.restyle('atlas-plot',{visible:$('show-rn').checked},[2]);});$('show-affine').addEventListener('change',()=>{if(plotReady)Plotly.restyle('atlas-plot',{visible:$('show-affine').checked},[4,5]);});$('save').addEventListener('click',async()=>{if(!lastRequest)return;$('save').disabled=true;try{const saved=await api('/api/save',lastRequest);$('save-status').textContent='Saved: '+saved.saved_to;}catch(e){$('save-status').textContent=e.message;}finally{$('save').disabled=!lastRequest;}});
(async()=>{try{[config,meshes]=await Promise.all([api('/api/config'),api('/meshes.json')]);$('dataset').innerHTML=Object.keys(config.datasets).map(id=>`<option value="${escapeText(id)}">${escapeText(id)}</option>`).join('');$('dataset').value=config.default_dataset;$('dataset').disabled=false;$('version').textContent='v'+config.version;$('data-location').textContent=config.data_root;$('bundle-version').textContent=config.bundle_id;updateDataset();await initPlot();const example=config.datasets[$('dataset').value].examples[0];$('coordinates').value='['+example.xyz.join(', ')+']';$('example').value='0';$('check').disabled=false;await runCheck();}catch(e){$('error').textContent='The app could not start: '+e.message;$('error').hidden=false;}})();
